name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: # Emon ekta button dibe jeta diye tumi manually build start korte parbe

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Build Flet APK
        run: requirements.txt build apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NICU_Smart_Bill_APK
          path: build/apk/*.apk